disabled_rules:
 - multiple_closures_with_trailing_closure
 - line_length
 - todo
 - trailing_whitespace
 - identifier_name
 - function_body_length
 - cyclomatic_complexity
 - type_body_length
 - file_length
